### ISSUE TITLE
OIP-1 : OIP Purpose and Guidelines

### ISSUE THREAD

**Issue by unnawut** [omisego/OIP#1]
The internal exchange mechanism design and the discussions have been moved to #2.

Going forward, the OIP-1 will contain the purpose and guideline for creating, submitting, reviewing and maintaining OIPs.

---

Discussion notes:
- Okay to create Issues for discussions. But no formal reviews are done in Issues. Issues get treated the same level as forum or chat discussions.
- To enter a formal review. Convert the Issue to a PR in the to-be-defined OIP template. Formal review happens in the PR.
- Use the PR ID as the OIP number. Okay to skip some numbers.

**Comment by ripzery** [comment]
# Question about `exchange_account_id`:
Let's say we have accounts `a1`, `a2`, `a3` and `master`.  `a1` want to do **Exchange transaction** or **Exchange transfer** with `a2`. The question is how does `a1` know which account has sufficient fund to make the exchange successful? Is it required to call `list_wallets` first? 

I also wonder that should `a1` interest about which account is going to act as an `Exchange`?
If `a1` doesn't have any reason to interest, then is it possible to remove an `exchange_account_id` and the eWallet will automatically pick some account that has sufficient fund with some priority mechanism to make the exchange successful? When the API cannot find an account which has enough fund, then return some error.

**Comment by unnawut** [comment]
I have two scenarios while designing this:

**Scenario 1: Enterprises - Large entities that need multiple accounts.**
  1. `master` account
  2. `a1` for branch1
  3. `a2` for branch2
  4. `a3` as a dedicated exchange account
  5. `a4` for a "June 8 - June 30 Summer Sale Point Exchange" program

Having these accounts enable the entities to control budget & funds for their logical groups easily.

I anticipate these entities will want exchanges to happen with a specific account in order to manage their funds accurately. The system should not simply exchange with an account that has sufficient fund and hence `exchange_account_id` is needed.

**Scenario 2: SMEs - Entities that need only one or relatively few accounts.**

But not all ewallet providers will need a complex account setup, and having `master` as their exchange account is sufficient enough. Hence the Rationale #&#xfeff;2 for defaulting to master account.

Although I'm not so sure if defaulting to `master` account is a good enough idea since this means not providing `exchange_account_id` in the Enterprise scenario will default to `master` account which might not be desirable.

**Comment by unnawut** [comment]
Actually since now `/user.credit_wallet` and `/user.credit_wallet` also requires the `account_id` input ([ref](https://github.com/omisego/ewallet/pull/215)), it's probably good to be explicit about the `exchange_account_id` as well.

I'm inclined to remove an `exchange_account_id` default value out of this RFC unless anyone disagrees.

**Comment by T-Dnzt** [comment]
I agree, let's make the `exchange_account_id` mandatory since we've started doing that everywhere. Other than that, looks good to me! I have some doubts about the exchange being made by an account on behalf of a user instead of the user getting the exchanged value and that value being transferred to the other user afterwards... but I guess it removes a transaction in the user's logs that they don't really care about.

- Let's not use `metadata` to store internal values, we can add more columns if needed.
- The type for the `Transfer` should probably be `internal_exchange` if we really want to have a type for that. Thoughts?

**Comment by sirn** [comment]
Shouldn't OIP documents be a PR and we revise per comments, then we have team member approve it if it's OK with majority? Even though GitHub now show edits I don't think it's very useful for documenting…
