### ISSUE TITLE
OIP-16: Fallback mechanism when relying on multiple Ethereum clients

### ISSUE THREAD

**Issue by unnawut** [omisego/OIP#16]
# Simple Summary

Consuming multiple Ethereum clients is pretty hard. Nodes become out of sync, competing chains, etc. At the same time, the ability to consume multiple Ethereum clients is important for resiliency.

This OIP attempts to lay down all common scenarios and suggest ways to deal with them.

# Motivation

Designing the fallback mechanism for Ethereum clients can be quite an effort as you will see below. This OIP hopes to draw a guideline on typical failures and discrepancies that we can expect from consuming multiple clients, regardless of being the same or of different implementations. So any future design/implementation for resiliency could make use of this guideline, not limited to Potterhat as defined in OIP-15 (#15).

# Specification

## Scenario 1 - Sync Delayed
A client stops reporting new blocks, but resume back after a while.

- Continue broadcasting blocks from the active node
- Alert of a `:node_delayed` after a pre-configured `:block_delay_tolerance` threshold
- Alert of a `:node_caughtup` when the delayed node is up to the same block height

![IMG_0041](https://user-images.githubusercontent.com/921194/56650586-89e15000-66b1-11e9-8958-9a0e57abd25c.JPG)

## Scenario 2 - Sync Delayed & Never Recovered
A client stops reporting new blocks, never recovered.

- Continue broadcasting blocks from the active node
- Alert of a `:node_delayed` after a pre-configured `:block_delay_tolerance` threshold
- Restart the unresponsive node

![IMG_0042](https://user-images.githubusercontent.com/921194/56650540-733af900-66b1-11e9-8c1c-3c80e7e38aad.JPG)

## Scenario 3 - Diverged & Converged
For the same block height, one client reports a block, another client reports another block. But eventually a chain reorg occurs and both clients are in sync again.

- Pick one node (based on pre-configured priority) to broadcast from
- Alert of `:node_diverged`immediately
- Alert of `:chain_reorg` when the nodes converge
- Broadcast a chain reorg event

![IMG_0043](https://user-images.githubusercontent.com/921194/56650549-77ffad00-66b1-11e9-8247-ed1f8627d424.JPG)

## Scenario 4 - Diverged & Never Converged
2 or more clients report different blocks for the same block height, never reconciled. Probably a hard fork.

- Pick one node (based on pre-configured priority) to broadcast from
- Alert of `:node_diverged` immediately`
- Stops broadcasting completely after a pre-configured `:max_conflicting_blocks_tolerance`

![IMG_0044](https://user-images.githubusercontent.com/921194/56650744-dc227100-66b1-11e9-8003-6615cc0aae05.JPG)

## Scenario 5 - Diverged & Delayed & Never Recovered:
2 clients reporting differing blocks for the same height. 1 client stopped reporting new blocks, and never recovered.

- Pick one node (based on pre-configured priority) to broadcast from
- Alert of `:node_diverged` immediately
- Alert of a `:node_delayed` after a pre-configured `:block_delay_tolerance` threshold
- Restart the unresponsive node
- Alert `:node_converged` if the node converged after restart

![IMG_0045](https://user-images.githubusercontent.com/921194/56650568-82ba4200-66b1-11e9-9b25-98bc64388956.JPG)

# Implementation

Work in progress at [omisego/potterhat](https://github.com/omisego/potterhat).

**Comment by InoMurko** [comment]
@unnawut hats off. Great write up!

Have you considered an alternative solution to `pick one node` in cases 3,4 and 5 (possibly 1 as well) by keeping a buffer of blocks? 
Same as you need `number of confirmations` on an exchange, you would buffer all clients blocks `(head - 10*)` 
where head is the block number of the fastest client. So you would always publish the block number which is the common denominator to all clients (but if they diverge more then 10* blocks, you would sign them off as bad clients). 

* 10 is a made up number

**Comment by unnawut** [comment]
You're right. That would solve a lot of problem and totally implementable. Although I'm not sure if these limitations is a dealbreaker...

- There was a suggestion to wait for 12 confirmations, [but back in 2016](https://ethereum.stackexchange.com/questions/183/how-should-i-handle-blockchain-forks-in-my-dapp/203#203).
- The recent block time is around 13 seconds, [according to Etherscan](https://etherscan.io/chart/blocktime).
- The recorded maximum block time around 30 seconds, also [according to Etherscan](https://etherscan.io/chart/blocktime).

This means the block delay from Potterhat could range from 2.6 minutes to 6 minutes. And since this is invisible to Potterhat's consumers, the consumers may also similarly wait for more block confirmations, adding another extra delay.

Not sure if above is acceptable. If yes then that would simplify Potterhat a lot and make this library more focused on metrics, alerts, and a total-meltdown fuse.

If not, then I think we still need to do node-switching. 🤔
